package com.company.rk.service.robert;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-09-23T15:55:47.138+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.rk.company.com/service/Robert/", name = "Robert")
@XmlSeeAlso({com.company.rk.schema.robertschema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Robert {

    @WebResult(name = "secondOperationResponse", targetNamespace = "http://www.rk.company.com/schema/RobertSchema", partName = "secondOperationResponse")
    @WebMethod(operationName = "SecondOperation", action = "http://www.rk.company.com/service/Robert/SecondOperation")
    public com.company.rk.schema.robertschema.SecondOperationResponseType secondOperation(
        @WebParam(partName = "secondOperationRequest", name = "secondOperationRequest", targetNamespace = "http://www.rk.company.com/schema/RobertSchema")
        com.company.rk.schema.robertschema.SecondOperationRequestType secondOperationRequest
    );
}
