package com.company.pm.pawel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-09-20T17:11:09.950+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.pm.company.com/Pawel/", name = "Pawel")
@XmlSeeAlso({com.company.pm.schema.pawel.ObjectFactory.class})
public interface Pawel {

    @WebResult(name = "out", targetNamespace = "http://www.pm.company.com/schema/Pawel")
    @RequestWrapper(localName = "FirstOperation", targetNamespace = "http://www.pm.company.com/schema/Pawel", className = "com.company.pm.schema.pawel.FirstOperationType")
    @WebMethod(operationName = "FirstOperation", action = "http://www.pm.company.com/Pawel/FirstOperation")
    @ResponseWrapper(localName = "FirstOperationResponse", targetNamespace = "http://www.pm.company.com/schema/Pawel", className = "com.company.pm.schema.pawel.FirstOperationResponseType")
    public java.lang.String firstOperation(
        @WebParam(name = "in", targetNamespace = "http://www.pm.company.com/schema/Pawel")
        java.lang.String in
    );
}
