package com.company.pm.pawel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-09-20T17:11:09.959+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "Pawel", 
                  wsdlLocation = "file:/D:/JBOSS_FUSE/pluralsight/apache-cxf-camel-soap-to-rest/src/main/resources/wsdl/Pawel.wsdl",
                  targetNamespace = "http://www.pm.company.com/Pawel/") 
public class Pawel_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.pm.company.com/Pawel/", "Pawel");
    public final static QName PawelSOAP = new QName("http://www.pm.company.com/Pawel/", "PawelSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/JBOSS_FUSE/pluralsight/apache-cxf-camel-soap-to-rest/src/main/resources/wsdl/Pawel.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Pawel_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/JBOSS_FUSE/pluralsight/apache-cxf-camel-soap-to-rest/src/main/resources/wsdl/Pawel.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Pawel_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Pawel_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Pawel_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Pawel_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Pawel_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Pawel_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Pawel
     */
    @WebEndpoint(name = "PawelSOAP")
    public Pawel getPawelSOAP() {
        return super.getPort(PawelSOAP, Pawel.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Pawel
     */
    @WebEndpoint(name = "PawelSOAP")
    public Pawel getPawelSOAP(WebServiceFeature... features) {
        return super.getPort(PawelSOAP, Pawel.class, features);
    }

}
