package com.company.rk.robert;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-09-20T17:11:09.555+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.rk.company.com/Robert/", name = "Robert")
@XmlSeeAlso({com.company.rk.schema.robert.ObjectFactory.class})
public interface Robert {

    @WebResult(name = "out", targetNamespace = "http://www.rk.company.com/schema/Robert")
    @RequestWrapper(localName = "SecondOperation", targetNamespace = "http://www.rk.company.com/schema/Robert", className = "com.company.rk.schema.robert.SecondOperationType")
    @WebMethod(operationName = "SecondOperation", action = "http://www.rk.company.com/Robert/SecondOperation")
    @ResponseWrapper(localName = "SecondOperationResponse", targetNamespace = "http://www.rk.company.com/schema/Robert", className = "com.company.rk.schema.robert.SecondOperationResponseType")
    public java.lang.String secondOperation(
        @WebParam(name = "in", targetNamespace = "http://www.rk.company.com/schema/Robert")
        java.lang.String in
    );
}
